RealState/RSM/Controllers/NomineeController.cs
using RSM.BLL;
using RSM.BOL.Models;
using RSM.DAL.DatabaseService;
using System;
using System.Web.Mvc;

namespace RSM.Controllers
{
    public class NomineeController : Controller
    {
        private ImageValidation _imageValidation = new ImageValidation();
        private DBOperations_Nominees _dbOperations = new DBOperations_Nominees();

        public ActionResult ViewNominees()
        {
            int ownerId = (int)Session["ownerId"];
            // Fetch nominees for the selected owner
            var nominees = _dbOperations.GetNomineeByOwnerId(ownerId);

            //CommentedByMUI
            //ViewBag.OwnerID = ownerId;
            //ViewBag.PropertyID = propertyId;
            return View(nominees);
        }
        public ActionResult GetSelectedNominee(int nomineeId)
        {
            Session["nomineeId"] = nomineeId;
            return RedirectToAction("ConfirmSale", "PropertySell");
        }

        public ActionResult AddNominee(/*int ownerID*/)
        {
            Nominee nominee = new Nominee {
                Name = "Name",
                CNIC = "45454",
                Relation = RelationType.Friend,
                //Relation = RelationType.Friend,
                SODOWO = "So/Do/Wo",
                DOB = DateTime.Now.ToString("yyyy-MM-dd"),
                CellNo = "5644",
                Gender  = "Male",
                Address = "jhfudb hf ",
                ImagePath = "~/SystemImages/NoUserImage.png",
                OwnerId = (int)TempData["OwnerId"]
            };

          
            
            return View(nominee);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddNominee(Nominee nominee)
        {
            if (ModelState.IsValid)
            {
                if (nominee.ImageFile != null)
                {
                    //image validaton logic (checks for prefered extension and size)
                    if (_imageValidation.IsValidImage(nominee.ImageFile))
                    {
                        var path = _imageValidation.SaveImageOnServer(nominee.ImageFile);
                        var isDataInserted = _dbOperations.InsertNomineeData(nominee, path);


                        ViewBag.Message = isDataInserted ? "<script>alert('Record Inserted')</script>" : "<script>alert('Record not Inserted')</script>";
                    }
                    else
                        ViewBag.Message = "<script>alert('Invalid Image type, only png, jpg and jpeg files are supported')</script>";
                }
                else
                {
                    var isDataInserted = _dbOperations.InsertNomineeData(nominee);

                    ViewBag.Message = isDataInserted ? "<script>alert('Record Inserted')</script>" : "<script>alert('Record not Inserted')</script>";
                }
                return RedirectToAction("ViewOwners", "Owner");

            }
            ModelState.Clear();
            return View();
        }
    }

}

RealState/RSM/Views/Nominee/AddNominee.cshtml
@model RSM.BOL.Models.Nominee

@{
    ViewBag.Title = "AddNominee";
}

<h2>AddNominee</h2>


@using (Html.BeginForm("AddNominee", "Nominee", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Nominee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.OwnerId)

    @*---Name---*@
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>


    @*---CNIC---*@
    <div class="form-group">
        @Html.LabelFor(model => model.CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CNIC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CNIC, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---Relation---*@
    <div class="form-group">
        @Html.LabelFor(model => model.Relation, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-9 col-sm-9 col-xs-12">
            @Html.EnumDropDownListFor(model => model.Relation, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Relation, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---SO/Do/Wo---*@
    <div class="form-group">
        @Html.LabelFor(model => model.SODOWO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SODOWO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SODOWO, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---DOB---*@
    <div class="form-group">
        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---Cell No---*@
    <div class="form-group">
        @Html.LabelFor(model => model.CellNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CellNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CellNo, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---Gender---*@
    <div class="form-group">
        @Html.LabelFor(model => model.Gender, "Gender", new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-9 col-sm-9 col-xs-12">
            <label>
                @Html.RadioButtonFor(model => model.Gender, "Male", new { @id = "gender-male" }) Male
            </label>
            <label>
                @Html.RadioButtonFor(model => model.Gender, "Female", new { @id = "gender-female" }) Female
            </label>
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---Address---*@
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    @*---Image---*@
    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" />
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealState/RSM/Views/Nominee/ViewNominees.cshtml
@model IEnumerable<RSM.BOL.Models.Nominee>

@*CommentedByMUI*@
@*@{
    int propertyId = ViewBag.PropertyID;
    int ownerId = ViewBag.OwnerID;
}*@

@{
    ViewBag.Title = "ViewNominees";
}

<h2>ViewNominees</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CNIC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Relation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SODOWO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CellNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CNIC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Relation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SODOWO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CellNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.NomineeId }) |
                <a href="@Url.Action("GetSelectedNominee", "Nominee", new { nomineeId = item.NomineeId})" class="btn btn-success">Confirm</a>

            </td>
        </tr>
    }

</table>