RealState/RSM/Controllers/PropertyController.cs
using Microsoft.SqlServer.Server;
using Newtonsoft.Json.Linq;
using RSM.BOL.Models;
using RSM.DAL.Context;
using RSM.DAL.DatabaseService;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RSM.Controllers
{
    public class PropertyController : Controller
    {
    private DBOperations_Property _dbOperations = new DBOperations_Property();

        // GET: Property
        private readonly RSMContext _ctx;
        public PropertyController()
        {
            _ctx = new RSMContext();
        }
        //[HttpGet]
        public ActionResult AddProperty()
        {
            Property property = new Property();
            

            return View();
        }
        [HttpPost]
        public ActionResult AddProperty(Property property)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _ctx.Properties.Add(property);
                    _ctx.SaveChanges();
                    return RedirectToAction("ViewProperties");

                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var validationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        // Log or display the error
                        System.Diagnostics.Debug.WriteLine($"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");
                    }
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult EditProperty(int Id)
        {
            
            var data = _ctx.Properties.Find(Id);
            //string idString = EncodeHash(data.ID);
            //data.ID = Convert.ToInt16(idString);
            return View(data);
        }
        //public static string EncodeHash(int id)
        //{
        //    using (SHA256 sha256 = SHA256.Create())
        //    {
        //        byte[] idBytes = BitConverter.GetBytes(id);
        //        byte[] hashBytes = sha256.ComputeHash(idBytes);
        //        return BitConverter.ToString(hashBytes).Replace("-", ""); // Converts byte array to hex string
        //    }
        //}
        [HttpPost]
        public ActionResult EditProperty(Property model)
        {
            //var data = _ctx.Properties.Find(model.PropertyID);
            //if (data != null)
            //{
                _ctx.Entry(model).State=EntityState.Modified;
                _ctx.SaveChanges();
            //}
            return RedirectToAction("ViewProperties");
        }

        public ActionResult ViewProperties()
        {
            var list = _ctx.Properties.ToList();
            return View(list);
        }

        public ActionResult GetSelectedProperty(int propertyID)
        {
            Session["propertyID"] = propertyID;

            //redirecting to owners viewOwners Page
            return RedirectToAction("ViewOwners", "Owner");
        }

      

        public ActionResult Delete(int id)
        {
            var list = _ctx.Properties.Find(id);
            _ctx.Properties.Remove(list);
            _ctx.SaveChanges();
            return RedirectToAction("ViewProperties");
        }
   

        private Property CreateDummyData()
        {
            return new Property
            {
                PlotNo = "D-97",
                PropertyType = PropertyType.Commercial,
                PropertyStatus = PropertyStatus.Available,
            };

        }


        public ActionResult GetPropertiesByOwnerId(int ownerId)
        {
            var properties=_dbOperations.GetPropertiesByOwner(ownerId).Count();
            
            return View();
        }
    }
}

RealState/RSM/Views/Property/AddProperty.cshtml
@model RSM.BOL.Models.Property
<div class="col-md-6 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Form Design <small>different form elements</small></h2>
            
            @*<ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#">Settings 1</a>
                    </li>
                    <li>
                        <a href="#">Settings 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>*@
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            @using (Html.BeginForm("AddProperty", "Property", FormMethod.Post,
                new { @class = "form-horizontal form-label-left input_mask", @id = "myForm", @enctype = "multipart/form-data" }))
            {
                <div class="form-group">

                    @Html.LabelFor(model => model.PlotNo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.PlotNo, new { htmlAttributes = new { @class = "form-control", placeholder = "PlotNo" } })
                        @Html.ValidationMessageFor(model => model.PlotNo, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectName, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @Id = "projName", @class = "form-control", placeholder = "ProjectName" } })
                        @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Block, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.Block,
new
{
    htmlAttributes = new { @Id = "block", @class = "form-control", placeholder = "Block" }
})
                        @Html.ValidationMessageFor(model => model.Block, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Size, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.Size,"Select Size", new {Id = "block", @class = "form-control", placeholder = "Block" })
                        @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PropertyType, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.PropertyType, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.North, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.North, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.North, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.East, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.East, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.East, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.West, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.West, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.West, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.South, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.South, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.South, "", new { @class = "text-danger" })

                    </div>
                </div>
               
                <div class="form-group">
                    @Html.LabelFor(model => model.PropertyStatus, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.PropertyStatus,new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropertyStatus, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        @*<button type="button" class="btn btn-primary">Cancel</button>*@
                        <a href="@Url.Action("ViewProperties","Property")" class="btn btn-primary">ViewList</a>
                        @*<button class="btn btn-primary">ViewList</button>*@
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>

            }

        </div>
    </div>
</div>

RealState/RSM/Views/Property/Create.cshtml
@model RSM.BOL.Models.Property
<div class="col-md-6 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Form Design <small>different form elements</small></h2>
            
            @*<ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#">Settings 1</a>
                    </li>
                    <li>
                        <a href="#">Settings 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>*@
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            @using (Html.BeginForm("Create", "Property", FormMethod.Post,
                new { @class = "form-horizontal form-label-left input_mask", @id = "myForm", @enctype = "multipart/form-data" }))
            {
                <div class="form-group">

                    @Html.LabelFor(model => model.PlotNo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.PlotNo, new { htmlAttributes = new { @class = "form-control", placeholder = "PlotNo" } })
                        @Html.ValidationMessageFor(model => model.PlotNo, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectName, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @Id = "projName", @class = "form-control", placeholder = "ProjectName" } })
                        @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Block, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.Block,
new
{
    htmlAttributes = new { @Id = "block", @class = "form-control", placeholder = "Block" }
})
                        @Html.ValidationMessageFor(model => model.Block, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Size, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.DropDownListFor(model => model.Size, new SelectList(ViewBag.SizeList, "Value", "Text"),  // Placeholder text
new { @Id = "block", @class = "form-control", placeholder = "Block" })
                        @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PropertyType, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.DropDownListFor(model => model.PropertyType, (SelectList)ViewBag.PropertyList,  // Placeholder text
                        new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.North, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.North, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.North, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.East, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.East, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.East, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.West, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.West, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.West, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.South, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.South, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.South, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.StreetNo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.StreetNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StreetNo, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList,  // Placeholder text
 new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })

                    </div>
                </div>
                @*<label>Gender *:</label>
            <p>
                M:
                <input type="radio" class="flat" name="gender" id="genderM" value="M" checked="" required /> F:
                <input type="radio" class="flat" name="gender" id="genderF" value="F" />
            </p>*@
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        @*<button type="button" class="btn btn-primary">Cancel</button>*@
                        
                        <a href="@Url.Action("Index","Property")" class="btn btn-primary">ViewList</a>
                        @*<button class="btn btn-primary">ViewList</button>*@
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>

            }

        </div>
    </div>
</div>

RealState/RSM/Views/Property/EditProperty.cshtml
@model RSM.BOL.Models.Property
<div class="col-md-6 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>
                Form Design <small>different form elements</small>
            </h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            @using (Html.BeginForm("EditProperty", "Property", FormMethod.Post,
                new { @class = "form-horizontal form-label-left input_mask", @id = "myForm", @enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model=>model.PropertyID)
                <div class="form-group">

                    @Html.LabelFor(model => model.PlotNo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.PlotNo, new { htmlAttributes = new { @class = "form-control", placeholder = "PlotNo" } })
                        @Html.ValidationMessageFor(model => model.PlotNo, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectName, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @Id = "projName", @class = "form-control", placeholder = "ProjectName" } })
                        @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Block, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.Block,
new
{
    htmlAttributes = new { @Id = "block", @class = "form-control", placeholder = "Block" }
})
                        @Html.ValidationMessageFor(model => model.Block, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Size, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.Size, new { @Id = "block", @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PropertyType, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.PropertyType, new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.North, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.North, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.North, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.East, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.East, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.East, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.West, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.West, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.West, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.South, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.South, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.South, "", new { @class = "text-danger" })

                    </div>
                </div>
               
                <div class="form-group">
                    @Html.LabelFor(model => model.PropertyStatus, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        @Html.EnumDropDownListFor(model => model.PropertyStatus, new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.PropertyStatus, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <a href="@Url.Action("ViewProperties","Property")" class="btn btn-primary">Back</a>

                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>

            }

        </div>
    </div>
</div>

RealState/RSM/Views/Property/ViewProperties.cshtml
@model IEnumerable<RSM.BOL.Models.Property>
<div class="form-group">
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        @*<div class="x_title">
                <h2>Default Example <small>Users</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>*@
        <div class="x_content">
            @*<p class="text-muted font-13 m-b-30">
                    DataTables has most features enabled by default, so all you need to do to use it with your own tables is to call the construction function: <code>$().DataTable();</code>
                </p>*@
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.PlotNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProjectName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Block)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Size)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PropertyType)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.North)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.East)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.West)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.South)
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>


                <tbody>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PlotNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProjectName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Block)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Size)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PropertyType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.North)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.East)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.West)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.South)
                            </td>

                            <td>
                                @Html.ActionLink("Edit", "EditProperty", new { id = item.PropertyID }, new { @class = "btn btn-info btn-rounded" }) |
                                @Html.ActionLink("Print", "Details", new { id = item.PropertyID }, new { @class = "btn btn-info btn-rounded" })
                                @Html.ActionLink("Sell", "GetSelectedProperty", "Property", new { propertyId = item.PropertyID}, new { @class = "btn btn-success" })
                            </td>
                        </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>