RealState/RSM/Controllers/OwnerController.cs
using RSM.BOL.Models;
using System;
using System.Web.Mvc;
using RSM.BLL;
using RSM.DAL.DatabaseService;
using RSM.DAL.Context;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity.Core.Metadata.Edm;

namespace RSM.Controllers
{
    public class OwnerController : Controller
    {
        private ImageValidation _imageValidation = new ImageValidation();
        private DBOperations_Owners _dbOperations = new DBOperations_Owners();

        public ActionResult ViewOwners(/*int propertyId = 0, bool isSelectionMode = false*/)
        {
            //fetch All Owners
            var owners = _dbOperations.GetOwners();

            //save property id get property page to pass it ViewownerPage
            //ViewBag.PropertyID = propertyId;
            return View(owners);
        }

        public ActionResult GetSelectedOwner(int ownerId)
        {
            Session["ownerId"] = ownerId;
            return RedirectToAction("ViewNominees", "Nominee");
        }




        public ActionResult AddOwner()
        {
            Owner ownerDummy = new Owner
            {
                FirstName = "Haider",
                LastName = "ALi",
                CNIC = "6556546",
                CellNo = "35265656",
                Gender = "Male",
                ContactNo = "654856485",
                Address = "Gulshan hadeed",
                ImagePath = "~/SystemImages/NoUserImage.png",
                SODOWO = "jsdujsdh",
                DOB = DateTime.Now.ToString("yyyy-MM-dd"),
            };
            return View(ownerDummy);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddOwner(Owner ownerData)
        {
            if (ModelState.IsValid)
            {
                if (ownerData.ImageFile != null)
                {
                    //image validaton logic (checks for prefered extension and size)
                    if (_imageValidation.IsValidImage(ownerData.ImageFile))
                    {
                        var path = _imageValidation.SaveImageOnServer(ownerData.ImageFile);
                        var isDataInserted = _dbOperations.InsertOwnerData(ownerData, path);


                        ViewBag.Message = isDataInserted ? "<script>alert('Record Inserted')</script>" : "<script>alert('Record not Inserted')</script>";
                    }
                    else
                        ViewBag.Message = "<script>alert('Invalid Image type, only png, jpg and jpeg files are supported')</script>";
                }
                else
                {
                    var isDataInserted = _dbOperations.InsertOwnerData(ownerData);

                    ViewBag.Message = isDataInserted ? "<script>alert('Record Inserted')</script>" : "<script>alert('Record not Inserted')</script>";
                }
                TempData["OwnerId"] = ownerData.OwnerID;
                return RedirectToAction("AddNominee", "Nominee");
            }

            return View();
        }
       
    }
}




        
        

RealState/RSM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="~/ProjectAssets/production/images/favicon.ico" type="image/ico" />

    <title>Gentelella Alela! | </title>
    <!-- Bootstrap -->
    <link href="~/assets/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/assets/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/assets/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="~/assets/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="~/assets/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="~/assets/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/assets/build/css/custom.min.css" rel="stylesheet">
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="~/assets/production/images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>John Doe</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    @Html.Partial("~/Views/PartialViews/_Sidebar.cshtml")
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>
            @Html.Partial("~/Views/PartialViews/Header.cshtml")
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        @*<div class="title_left">
                            <h3>Form Elements</h3>
                        </div>

                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>*@
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        @RenderBody()

                    </div>
                </div>
            </div>
            <!-- /page content -->
            @*<hr />*@
            @Html.Partial("~/Views/PartialViews/_Footer.cshtml")
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/assets/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/assets/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/assets/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/assets/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/assets/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- jQuery Sparklines -->
    <script src="~/assets/vendors/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- morris.js -->
    <script src="~/assets/vendors/raphael/raphael.min.js"></script>
    <script src="~/assets/vendors/morris.js/morris.min.js"></script>
    <!-- gauge.js -->
    <script src="~/assets/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="~/assets/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- Skycons -->
    <script src="~/assets/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="~/assets/vendors/Flot/jquery.flot.js"></script>
    <script src="~/assets/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="~/assets/vendors/Flot/jquery.flot.time.js"></script>
    <script src="~/assets/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="~/assets/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="~/assets/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="~/assets/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="~/assets/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="~/assets/vendors/DateJS/build/date.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/assets/vendors/moment/min/moment.min.js"></script>
    <script src="~/assets/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- iCheck -->
    <script src="~/assets/vendors/iCheck/icheck.min.js"></script>

    <!-- Datatables -->
    <script src="~/assets/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/assets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/assets/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/assets/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/assets/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/assets/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/assets/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/assets/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/assets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/assets/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/assets/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/assets/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/assets/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/assets/vendors/pdfmake/build/vfs_fonts.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/assets/build/js/custom.min.js"></script>
        @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
        @RenderSection("scripts", required: false)
</body>
</html>

RealState/RSM/Views/Shared/_OwnerPartialView.cshtml
@model RSM.BOL.Models.Owner
@{
    int propertyId = ViewData["PropertyID"] != null ? (int)ViewData["PropertyID"] : 0;
}


<div class="col-md-4 col-sm-4 col-xs-12 profile_details">
    <div class="well profile_view">
        <div class="col-sm-12">
            <h4 class="brief"><i>@Model.OwnerType</i></h4>
            <div class="left col-xs-7">
                <h2>@Model.FirstName @Model.LastName</h2>
                <p><strong>About: </strong> Web Designer / UI. </p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-credit-card-alt"></i>  CNIC: @Model.CNIC</li>
                    <li><i class="fa fa-phone"></i>  Phone #: @Model.CellNo </li>
                </ul>
            </div>
            <div class="right col-xs-5 text-center">
                <img src="@Url.Content(Model.ImagePath)" alt="" class="img-circle img-responsive">
            </div>
        </div>
        <div class="col-xs-12 bottom text-center">
            <div class="col-xs-12 emphasis">

                @*---ViewNomineesButton---*@
                <button type="button" class="btn btn-primary btn-round">
                    <i class="fa fa-users"> </i> Nominees
                </button>
                @*---EditOwnerButton---*@
               
                <a href=" @Url.Action("EditOwner", "Owner", new { ownerId = Model.OwnerID})"
                   class="btn btn-primary btn-round">
                    <i class="fa fa-edit"> </i> Edit
                </a>

                @*---EditDeleteButton---*@

                <a href=" @Url.Action("Delete", "Owner", new { ownerId = Model.OwnerID})"
                   class="btn btn-danger btn-round">
                    <i class="fa fa-trash"> </i> Delete
                </a>

                @*--SelectButton---*@

                <a href=" @Url.Action("GetSelectedOwner", "Owner", new { ownerId = Model.OwnerID})"
                   class="btn btn-success btn-round">
                    Select
                </a>

            </div>
        </div>
    </div>
</div>